// Auto-generated by sync-dto-to-typescript from server/POS.Domain/Entities/Product.cs
// Regenerate on change; manual edits may be overwritten.

export interface Product {
  id: string;
  name: string;
  sku: string;
  barcode: string;
  netPrice: number;
  taxRate: number;
  finalPrice: number; // La interfaz lo recibe como número ya calculado
  stock: number;
  /** Último costo de compra unitario; null/undefined si aún no hubo compras. */
  lastCost?: number | null;
  extendedDataJson: string;
  createdAt: string;
}
